version: 2

defaults: &defaults
  working_directory: ~/monstage
  docker:
    - image: circleci/ruby:2.5.2-node-browsers
    - image: circleci/postgres:10.6
      environment:
        POSTGRES_USER: monstage_test
        POSTGRES_PASSWORD: monstage_test
        POSTGRES_DB: monstage_test

bundle_restore_cache: &bundle_restore_cache
  restore_cache:
    name: Restore Bundler Package Cache
    key: bundle-install-v8-{{ arch }}-{{ checksum "Gemfile.lock" }}

bundle_save_cache: &bundle_save_cache
  save_cache:
    name: Save Bundler Package Cache
    key: bundle-install-v8-{{ arch }}-{{ checksum "Gemfile.lock" }}
    paths:
      - ~/vendor/bundle

bundle_install: &bundle_install
  run:
    name: Install Ruby Dependencies
    command: bundle install --path ~/vendor/bundle

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - *bundle_restore_cache
      - *bundle_install
      - *bundle_save_cache
  test:
    <<: *defaults
    parallelism: 3
    steps:
      - checkout
      - *bundle_restore_cache
      - *bundle_install
      - run:
          environment:
            DATABASE_URL: "postgres://monstage_test@localhost:5432/monstage_test"
          name: Create DB
          command: bundle exec rake db:create db:schema:load db:migrate RAILS_ENV=test
      - run:
          environment:
            DATABASE_URL: "postgres://monstage_test@localhost:5432/monstage_test"
          name: Run Tests, Splitted by Timings
          command: |
            COMMAND="bundle exec rake"
            echo $COMMAND
            eval $COMMAND
      - store_test_results:
          path: ~/test_results/testunit.xml

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
